[build]
  # Directorio que se publicar치
  publish = "dist"
  
  # Comando de build (npm install se ejecuta autom치ticamente antes)
  command = "npm install && npm run build"

[build.environment]
  # Versi칩n de Node.js
  NODE_VERSION = "18"

# Configuraci칩n de redirecciones (opcional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
